In [1]:
import numpy as np
import trimesh
import pyflex

In [8]:
cam_1_particle_fd = '/home/baoyu/2023/unified_dyn_graph/data/rope/camera_1/episode_0/0_particles.npy'
cam_2_particle_fd = '/home/baoyu/2023/unified_dyn_graph/data/rope/camera_2/episode_0/0_particles.npy'

In [9]:
# load particles
cam_1_particles = np.load(cam_1_particle_fd)
cam_2_particles = np.load(cam_2_particle_fd)

In [10]:
cam_1_particles

array([[ 1.3514287 ,  0.575     ,  0.05052212,  1.        ],
       [ 1.3109375 ,  0.575     ,  0.04925269,  1.        ],
       [ 1.2119898 ,  0.5759806 ,  0.05116613,  1.        ],
       [ 1.1395866 ,  0.575     ,  0.04835994,  1.        ],
       [ 1.0629978 ,  0.5763717 ,  0.05001925,  1.        ],
       [ 0.958927  ,  0.575     ,  0.04989383,  1.        ],
       [ 0.86249965,  0.575     ,  0.04893438,  1.        ],
       [ 0.76300955,  0.57500494,  0.0499623 ,  1.        ],
       [ 0.65892875,  0.57525945,  0.04993706,  1.        ],
       [ 0.5644988 ,  0.575     ,  0.04890922,  1.        ],
       [ 0.45892856,  0.57545465,  0.04995412,  1.        ],
       [ 0.3644999 ,  0.575     ,  0.04892484,  1.        ],
       [ 0.26093742,  0.5750136 ,  0.04942459,  1.        ],
       [ 0.16093734,  0.575     ,  0.04942431,  1.        ],
       [ 0.05892849,  0.5754586 ,  0.04994928,  1.        ],
       [-0.03550018,  0.575     ,  0.0489248 ,  1.        ],
       [-0.1390627 ,  0.

In [ ]:
cam_2_particles

In [7]:
cam_1_particles.shape

(26674, 4)

In [7]:
np.random.rand(1, 1, 4)

array([[[0.57987608, 0.54827175, 0.22697347, 0.13771355]]])

In [8]:
wkspc_w = 4
action = -wkspc_w + 2 * wkspc_w * np.random.rand(1, 1, 4)
action

array([[[-3.97005224,  2.03861417,  0.82938875,  2.79637198]]])

In [9]:
action_1 = np.load('/home/baoyu/2023/unified_dyn_graph/data/shirt/actions.npy')
action_2 = np.load('/home/baoyu/2023/unified_dyn_graph/data/shirt/camera_2/actions.npy')

In [11]:
action_1

array([[-0.51280338,  0.51529479,  0.86425962,  1.94707726],
       [ 0.03016625,  0.51443011,  0.52442104,  0.05195693],
       [ 0.32838815,  0.54590392,  1.89548016,  2.40055496],
       [ 0.52853233,  0.52084321,  0.4391928 ,  1.76951812],
       [ 0.08754858,  0.51355934,  0.35972683,  2.21594589]])

In [12]:
action_2

array([[-0.51300204,  0.51535857,  0.86406096,  1.94714104],
       [ 0.02210885,  0.51449007,  0.51636363,  0.0520169 ],
       [ 0.39224148,  0.52836263,  1.95933348,  2.38301367],
       [ 0.49471378,  0.505     ,  0.40537425,  1.75367491],
       [ 0.09445389,  0.55732459,  0.36663213,  2.25971114]])

In [3]:
actions = np.load('/home/baoyu/2023/unified_dyn_graph/data_sparse/shirt/actions.npy')
actions = actions.reshape(20, 5, 4)
actions

array([[[ 1.43178247,  1.38900696, -0.80188655,  0.38763775],
        [ 1.567092  ,  1.85465104, -0.63998449, -0.31743812],
        [-0.08009131, -0.42886082, -0.65799482, -0.20822864],
        [-1.91912641,  1.33047938, -1.26497791, -0.1784449 ],
        [ 0.55968409, -1.42658685, -0.59548166, -0.65086737]],

       [[-0.10559832, -1.25467063, -0.97790705,  0.06588422],
        [-1.9248408 ,  0.47054199, -0.27752464, -1.0192086 ],
        [ 1.6103939 , -0.20020004, -0.57998348,  0.05812264],
        [-0.7382866 , -0.54515692, -0.20389665, -1.31946484],
        [-1.59182076, -1.16449298, -0.20033687,  0.26448923]],

       [[-0.34252565, -0.10120999,  0.32747132,  0.44862233],
        [-1.94571346,  0.49138438,  0.83728189, -0.38681213],
        [ 0.03849751, -1.77714123,  0.96567367,  0.31012647],
        [ 1.52190356,  1.67294187,  0.05128683,  0.18700359],
        [-0.93844204,  0.09299221,  0.32350681,  0.04848649]],

       [[-1.96257318,  1.36936832, -1.12974118, -0.40976386],
  

In [12]:
particle_0 = np.load('/home/baoyu/2023/unified_dyn_graph/data_sparse/shirt/camera_1/episode_0/0_particles.npy')
particle_1 = np.load('/home/baoyu/2023/unified_dyn_graph/data_sparse/shirt/camera_1/episode_0/1_particles.npy')
particle_2 = np.load('/home/baoyu/2023/unified_dyn_graph/data_sparse/shirt/camera_1/episode_0/2_particles.npy')

In [9]:
print(particle_0.shape)
particle_0[:, :3]

(26674, 4)


array([[-1.2671502 ,  0.505     ,  0.00536735],
       [-1.1793748 ,  0.54683876,  0.45581502],
       [-1.2158709 ,  0.505     ,  0.00419856],
       ...,
       [ 0.36010194,  0.52932614, -0.20828149],
       [ 0.34881547,  0.5284405 , -0.23249821],
       [ 0.32512665,  0.505     , -0.22399262]], dtype=float32)

In [10]:
print(particle_1.shape)
particle_1[:, :3]

(26674, 4)


array([[-1.2671502 ,  0.505     ,  0.00536735],
       [-1.1793748 ,  0.54683876,  0.45581502],
       [-1.2158709 ,  0.505     ,  0.00419856],
       ...,
       [-0.17799059,  0.54928404, -0.28403887],
       [-0.20421197,  0.544764  , -0.28151518],
       [-0.20094289,  0.51115924, -0.2852092 ]], dtype=float32)

In [13]:
print(particle_2.shape)
particle_2[:, :3]

(26674, 4)


array([[-1.2673775 ,  0.505     ,  0.00510537],
       [-1.1874183 ,  0.5472362 ,  0.4544387 ],
       [-1.2160347 ,  0.505     ,  0.004006  ],
       ...,
       [-0.57403916,  0.53057766,  0.28411803],
       [-0.57425815,  0.5514829 ,  0.26752973],
       [-0.5913297 ,  0.5282298 ,  0.2495781 ]], dtype=float32)

In [8]:
import numpy as np

In [11]:
from scipy.spatial.distance import cdist

x = np.array([[2,1]])
y = np.array([[1,0], [2,3], [4,3]])

d = cdist(x,y)
d

array([[1.41421356, 2.        , 2.82842712]])

In [12]:
np.min(d)

1.4142135623730951

In [23]:
particle_0 = np.load('/home/baoyu/2023/unified_dyn_graph/data_dense/mustard_bottle/camera_1/episode_0/0_particles.npy')
particle_1 = np.load('/home/baoyu/2023/unified_dyn_graph/data_dense/mustard_bottle/camera_1/episode_0/1_particles.npy')
action_0 = np.load('/home/baoyu/2023/unified_dyn_graph/data_dense/mustard_bottle/actions.npy')

In [24]:
particle_0[:, [0, 2]]

array([[-0.21478087,  0.7313807 ],
       [-0.24413192,  0.03074625],
       [-0.24465683,  0.08074313],
       ...,
       [ 0.02107791,  0.7326958 ],
       [-0.00907233,  0.08221829],
       [-0.01589599,  0.73217785]], dtype=float32)

In [25]:
action_0 = action_0.reshape(2, 4)
action_0

array([[-1.77314809, -0.90937482, -0.1735031 ,  0.03147495],
       [-1.57636957, -0.10559832,  0.00413111, -0.01940584]])

In [26]:
action_0[0, 2:]

array([-0.1735031 ,  0.03147495])

In [37]:
np.where(particle_0[:, [0, 2]] == action_0[0, 2:])

(array([70, 70]), array([0, 1]))

In [39]:
particle_0[:, [0, 2]][763]

array([0.06189577, 0.68352413], dtype=float32)

In [30]:
particle_0[70]

array([-0.1735031 ,  0.5759315 ,  0.03147495,  0.1       ], dtype=float32)

In [42]:
x = np.array([1,2,3])
(x-2)**2

array([1, 0, 1])

In [12]:
import numpy as np
np.random.uniform(0, 0.1)

0.06954400388719517

In [14]:
import random
sample_size = 20
samples = [random.uniform(0, 5e-4) for _ in range(sample_size)]
samples

[0.0002555687414881901,
 0.00044696068491777646,
 0.00022721679957728597,
 0.00015852201110893395,
 0.0003761975867548927,
 5.109778512080915e-05,
 0.00027807427246633666,
 2.6929263554249462e-05,
 0.0003932375037429013,
 0.00011736252761205712,
 0.0002319212646853707,
 0.00048355548368891687,
 0.0003351328334429828,
 0.0003345698495233726,
 0.0001759785757983472,
 0.0004298791045686227,
 0.0002349984447150344,
 0.00015251696211214855,
 0.00025119332319031216,
 4.044575966551861e-05]

In [15]:
import random
import numpy as np

low, high = 0, 5e-4
sample_size = 20
num_strata = sample_size

strata_bounds = np.linspace(low, high, num_strata + 1)
samples = [np.random.uniform(strata_bounds[i], strata_bounds[i + 1]) for i in range(num_strata)]
print(samples)
# print(samples)

[2.4809250491531806e-05, 4.9592931477771274e-05, 6.544032635731598e-05, 9.20400793418651e-05, 0.00011038035107573681, 0.00013847536945736918, 0.00015993798394055113, 0.00019258813686619025, 0.00022356090293050427, 0.00023223299561380342, 0.00027164759366725416, 0.00029593402340225326, 0.00032206652895276514, 0.00034095810195213037, 0.00036382850835650935, 0.0003869933984044857, 0.00040304704278318814, 0.0004420328846102706, 0.0004529392679633176, 0.00047700787791787847]


In [16]:
particle_8 = np.load('/home/baoyu/2023/unified_dyn_graph/data_dense/rope/camera_1/episode_0/1_particles.npy')
particle_4 = np.load('/home/baoyu/2023/unified_dyn_graph/data_dense/rope/camera_1/episode_2/1_particles.npy')

In [17]:
particle_8

array([[ 1.4799491 ,  0.5834041 , -0.01094077,  1.        ],
       [ 1.4682177 ,  0.6212797 , -0.02865712,  1.        ],
       [ 1.4738672 ,  0.5974741 , -0.0189722 ,  1.        ],
       ...,
       [-0.8618243 ,  0.6253798 ,  1.0445763 ,  1.        ],
       [-0.85847306,  0.60615885,  1.0305048 ,  1.        ],
       [-0.8547507 ,  0.606319  ,  1.0090845 ,  1.        ]],
      dtype=float32)

In [19]:
particle_4 == particle_8

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       ...,
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])