In [1]:
import numpy as np
import trimesh
import pyflex

In [8]:
cam_1_particle_fd = '/home/baoyu/2023/unified_dyn_graph/data/rope/camera_1/episode_0/0_particles.npy'
cam_2_particle_fd = '/home/baoyu/2023/unified_dyn_graph/data/rope/camera_2/episode_0/0_particles.npy'

In [9]:
# load particles
cam_1_particles = np.load(cam_1_particle_fd)
cam_2_particles = np.load(cam_2_particle_fd)

In [10]:
cam_1_particles

array([[ 1.3514287 ,  0.575     ,  0.05052212,  1.        ],
       [ 1.3109375 ,  0.575     ,  0.04925269,  1.        ],
       [ 1.2119898 ,  0.5759806 ,  0.05116613,  1.        ],
       [ 1.1395866 ,  0.575     ,  0.04835994,  1.        ],
       [ 1.0629978 ,  0.5763717 ,  0.05001925,  1.        ],
       [ 0.958927  ,  0.575     ,  0.04989383,  1.        ],
       [ 0.86249965,  0.575     ,  0.04893438,  1.        ],
       [ 0.76300955,  0.57500494,  0.0499623 ,  1.        ],
       [ 0.65892875,  0.57525945,  0.04993706,  1.        ],
       [ 0.5644988 ,  0.575     ,  0.04890922,  1.        ],
       [ 0.45892856,  0.57545465,  0.04995412,  1.        ],
       [ 0.3644999 ,  0.575     ,  0.04892484,  1.        ],
       [ 0.26093742,  0.5750136 ,  0.04942459,  1.        ],
       [ 0.16093734,  0.575     ,  0.04942431,  1.        ],
       [ 0.05892849,  0.5754586 ,  0.04994928,  1.        ],
       [-0.03550018,  0.575     ,  0.0489248 ,  1.        ],
       [-0.1390627 ,  0.

In [ ]:
cam_2_particles

In [7]:
cam_1_particles.shape

(26674, 4)

In [7]:
np.random.rand(1, 1, 4)

array([[[0.57987608, 0.54827175, 0.22697347, 0.13771355]]])

In [8]:
wkspc_w = 4
action = -wkspc_w + 2 * wkspc_w * np.random.rand(1, 1, 4)
action

array([[[-3.97005224,  2.03861417,  0.82938875,  2.79637198]]])

In [9]:
action_1 = np.load('/home/baoyu/2023/unified_dyn_graph/data/shirt/actions.npy')
action_2 = np.load('/home/baoyu/2023/unified_dyn_graph/data/shirt/camera_2/actions.npy')

In [11]:
action_1

array([[-0.51280338,  0.51529479,  0.86425962,  1.94707726],
       [ 0.03016625,  0.51443011,  0.52442104,  0.05195693],
       [ 0.32838815,  0.54590392,  1.89548016,  2.40055496],
       [ 0.52853233,  0.52084321,  0.4391928 ,  1.76951812],
       [ 0.08754858,  0.51355934,  0.35972683,  2.21594589]])

In [12]:
action_2

array([[-0.51300204,  0.51535857,  0.86406096,  1.94714104],
       [ 0.02210885,  0.51449007,  0.51636363,  0.0520169 ],
       [ 0.39224148,  0.52836263,  1.95933348,  2.38301367],
       [ 0.49471378,  0.505     ,  0.40537425,  1.75367491],
       [ 0.09445389,  0.55732459,  0.36663213,  2.25971114]])

In [3]:
actions = np.load('/home/baoyu/2023/unified_dyn_graph/data_sparse/shirt/actions.npy')
actions = actions.reshape(20, 5, 4)
actions

array([[[ 1.43178247,  1.38900696, -0.80188655,  0.38763775],
        [ 1.567092  ,  1.85465104, -0.63998449, -0.31743812],
        [-0.08009131, -0.42886082, -0.65799482, -0.20822864],
        [-1.91912641,  1.33047938, -1.26497791, -0.1784449 ],
        [ 0.55968409, -1.42658685, -0.59548166, -0.65086737]],

       [[-0.10559832, -1.25467063, -0.97790705,  0.06588422],
        [-1.9248408 ,  0.47054199, -0.27752464, -1.0192086 ],
        [ 1.6103939 , -0.20020004, -0.57998348,  0.05812264],
        [-0.7382866 , -0.54515692, -0.20389665, -1.31946484],
        [-1.59182076, -1.16449298, -0.20033687,  0.26448923]],

       [[-0.34252565, -0.10120999,  0.32747132,  0.44862233],
        [-1.94571346,  0.49138438,  0.83728189, -0.38681213],
        [ 0.03849751, -1.77714123,  0.96567367,  0.31012647],
        [ 1.52190356,  1.67294187,  0.05128683,  0.18700359],
        [-0.93844204,  0.09299221,  0.32350681,  0.04848649]],

       [[-1.96257318,  1.36936832, -1.12974118, -0.40976386],
  

In [12]:
particle_0 = np.load('/home/baoyu/2023/unified_dyn_graph/data_sparse/shirt/camera_1/episode_0/0_particles.npy')
particle_1 = np.load('/home/baoyu/2023/unified_dyn_graph/data_sparse/shirt/camera_1/episode_0/1_particles.npy')
particle_2 = np.load('/home/baoyu/2023/unified_dyn_graph/data_sparse/shirt/camera_1/episode_0/2_particles.npy')

In [9]:
print(particle_0.shape)
particle_0[:, :3]

(26674, 4)


array([[-1.2671502 ,  0.505     ,  0.00536735],
       [-1.1793748 ,  0.54683876,  0.45581502],
       [-1.2158709 ,  0.505     ,  0.00419856],
       ...,
       [ 0.36010194,  0.52932614, -0.20828149],
       [ 0.34881547,  0.5284405 , -0.23249821],
       [ 0.32512665,  0.505     , -0.22399262]], dtype=float32)

In [10]:
print(particle_1.shape)
particle_1[:, :3]

(26674, 4)


array([[-1.2671502 ,  0.505     ,  0.00536735],
       [-1.1793748 ,  0.54683876,  0.45581502],
       [-1.2158709 ,  0.505     ,  0.00419856],
       ...,
       [-0.17799059,  0.54928404, -0.28403887],
       [-0.20421197,  0.544764  , -0.28151518],
       [-0.20094289,  0.51115924, -0.2852092 ]], dtype=float32)

In [13]:
print(particle_2.shape)
particle_2[:, :3]

(26674, 4)


array([[-1.2673775 ,  0.505     ,  0.00510537],
       [-1.1874183 ,  0.5472362 ,  0.4544387 ],
       [-1.2160347 ,  0.505     ,  0.004006  ],
       ...,
       [-0.57403916,  0.53057766,  0.28411803],
       [-0.57425815,  0.5514829 ,  0.26752973],
       [-0.5913297 ,  0.5282298 ,  0.2495781 ]], dtype=float32)

In [8]:
import numpy as np

In [11]:
from scipy.spatial.distance import cdist

x = np.array([[2,1]])
y = np.array([[1,0], [2,3], [4,3]])

d = cdist(x,y)
d

array([[1.41421356, 2.        , 2.82842712]])

In [12]:
np.min(d)

1.4142135623730951

In [23]:
particle_0 = np.load('/home/baoyu/2023/unified_dyn_graph/data_dense/mustard_bottle/camera_1/episode_0/0_particles.npy')
particle_1 = np.load('/home/baoyu/2023/unified_dyn_graph/data_dense/mustard_bottle/camera_1/episode_0/1_particles.npy')
action_0 = np.load('/home/baoyu/2023/unified_dyn_graph/data_dense/mustard_bottle/actions.npy')

In [24]:
particle_0[:, [0, 2]]

array([[-0.21478087,  0.7313807 ],
       [-0.24413192,  0.03074625],
       [-0.24465683,  0.08074313],
       ...,
       [ 0.02107791,  0.7326958 ],
       [-0.00907233,  0.08221829],
       [-0.01589599,  0.73217785]], dtype=float32)

In [25]:
action_0 = action_0.reshape(2, 4)
action_0

array([[-1.77314809, -0.90937482, -0.1735031 ,  0.03147495],
       [-1.57636957, -0.10559832,  0.00413111, -0.01940584]])

In [26]:
action_0[0, 2:]

array([-0.1735031 ,  0.03147495])

In [37]:
np.where(particle_0[:, [0, 2]] == action_0[0, 2:])

(array([70, 70]), array([0, 1]))

In [39]:
particle_0[:, [0, 2]][763]

array([0.06189577, 0.68352413], dtype=float32)

In [30]:
particle_0[70]

array([-0.1735031 ,  0.5759315 ,  0.03147495,  0.1       ], dtype=float32)

In [42]:
x = np.array([1,2,3])
(x-2)**2

array([1, 0, 1])

In [12]:
import numpy as np
np.random.uniform(0, 0.1)

0.06954400388719517

In [14]:
import random
sample_size = 20
samples = [random.uniform(0, 5e-4) for _ in range(sample_size)]
samples

[0.0002555687414881901,
 0.00044696068491777646,
 0.00022721679957728597,
 0.00015852201110893395,
 0.0003761975867548927,
 5.109778512080915e-05,
 0.00027807427246633666,
 2.6929263554249462e-05,
 0.0003932375037429013,
 0.00011736252761205712,
 0.0002319212646853707,
 0.00048355548368891687,
 0.0003351328334429828,
 0.0003345698495233726,
 0.0001759785757983472,
 0.0004298791045686227,
 0.0002349984447150344,
 0.00015251696211214855,
 0.00025119332319031216,
 4.044575966551861e-05]

In [1]:
import random
import numpy as np

low, high = 0, 5e-4
sample_size = 100
num_strata = sample_size

strata_bounds = np.linspace(low, high, num_strata + 1)
samples = [np.random.uniform(strata_bounds[i], strata_bounds[i + 1]) for i in range(num_strata)]
print(samples)
# print(samples)

[1.950909857790948e-06, 8.687648360437723e-06, 1.182058298337339e-05, 1.53974829729518e-05, 2.3326037057867297e-05, 2.8891640590632275e-05, 3.391873609419341e-05, 3.7185132521602345e-05, 4.312402467913132e-05, 4.8271100238516305e-05, 5.037850744014933e-05, 5.7149941730624815e-05, 6.313990132325158e-05, 6.702570690647773e-05, 7.067603797170393e-05, 7.80506400876549e-05, 8.070987361807036e-05, 8.936857779968512e-05, 9.178022982578783e-05, 9.929815459147133e-05, 0.00010357618497952861, 0.00010716913411264695, 0.00011391680850029549, 0.00011899636229287239, 0.00012235564681293559, 0.0001273247990906217, 0.00013177538264239703, 0.00013783055234083003, 0.0001422909810151374, 0.0001493009606163098, 0.00015072134994478244, 0.0001599637950109736, 0.000161786711787987, 0.00016872182146117847, 0.0001708979913015563, 0.00017862205258148664, 0.00018179334870709317, 0.00018603003778437497, 0.00019050767282492262, 0.0001956178011299653, 0.0002010086761168791, 0.0002054503097306306, 0.0002134172956438

In [47]:
low, high = 0.8, 1.5
np.random.rand() * (high - low) + low

1.0669620488694989

In [16]:
particle_8 = np.load('/home/baoyu/2023/unified_dyn_graph/data_dense/rope/camera_1/episode_0/1_particles.npy')
particle_4 = np.load('/home/baoyu/2023/unified_dyn_graph/data_dense/rope/camera_1/episode_2/1_particles.npy')

In [17]:
particle_8

array([[ 1.4799491 ,  0.5834041 , -0.01094077,  1.        ],
       [ 1.4682177 ,  0.6212797 , -0.02865712,  1.        ],
       [ 1.4738672 ,  0.5974741 , -0.0189722 ,  1.        ],
       ...,
       [-0.8618243 ,  0.6253798 ,  1.0445763 ,  1.        ],
       [-0.85847306,  0.60615885,  1.0305048 ,  1.        ],
       [-0.8547507 ,  0.606319  ,  1.0090845 ,  1.        ]],
      dtype=float32)

In [19]:
particle_4 == particle_8

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       ...,
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [1]:
import numpy as np
actions = np.load('/media/baoyu/sumsung/rope/episode_19/actions.npy')
steps = np.load('/media/baoyu/sumsung/rope/episode_19/steps.npy')
print('actions: ', actions)
print('steps: ', steps)

actions:  [[ 0.72313686 -0.54650354 -0.2221822   1.04283755]
 [ 0.7529604  -0.99781758 -0.12685899  1.48055729]
 [ 0.74697728 -1.44717033  1.38670427  1.50358264]
 [-0.20542012 -0.37561874  0.80852368  1.66269192]
 [-0.70923298  0.10267761  0.76103779  1.74936295]]
steps:  [ 60 133 186 236 299 354]


In [6]:
import numpy as np
for i in range(200):
    actions = np.load(f'/media/baoyu/sumsung/rope_2/rope/episode_{i}/actions.npy')
    steps = np.load(f'/media/baoyu/sumsung/rope_2/rope/episode_{i}/steps.npy')
    if steps.shape[0] == 5:
        print(i, 'actions: ', actions)
        print(i, 'steps: ', steps)

0 actions:  [[-1.12859894  0.36773575 -0.62444396 -0.15609152]
 [ 0.14622679 -1.30860256 -0.6317477   0.10777147]
 [-0.20045699 -1.06624696 -0.90639001 -0.00591974]
 [ 0.86243178  0.34929867 -0.81341242  0.234841  ]
 [ 0.60548304 -0.35723888 -1.39399098  0.29822262]]
0 steps:  [191 329 523 772 993]
1 actions:  [[ 0.49759089  0.40267574 -0.02984854  1.40746946]
 [-0.48514283 -0.87297096 -1.05186907  0.48386558]
 [ 0.44236046  0.73709495 -0.7932344   1.06780436]
 [ 0.64357565 -0.80870548 -0.87525538  1.4781517 ]
 [ 0.49310818  0.33965828 -1.49331513  0.66754753]]
1 steps:  [1209 1520 1683 1865 1968]
2 actions:  [[-0.66560389 -1.07705524 -0.23490734  1.44295915]
 [ 0.76156644  0.31400904 -0.79663038 -0.23201957]
 [-0.15138791 -1.12818467 -0.75937801  1.06590361]
 [-0.03971665 -1.1936897  -1.07078562  1.17683413]
 [-0.13440481 -1.39222113 -1.33817076  1.28338665]]
2 steps:  [2349 2462 2780 3109 3325]
3 actions:  [[-1.19590393 -1.29595996 -0.7993728   0.70699439]
 [ 0.5672936  -0.00676201 -

In [2]:
import numpy as np
for i in range(200):
    actions = np.load(f'/media/baoyu/sumsung/Tshirt/episode_{i}/actions.npy')
    steps = np.load(f'/media/baoyu/sumsung/Tshirt/episode_{i}/steps.npy')
    if steps.shape[0] == 5:
        print(i, 'actions: ', actions)
        print(i, 'steps: ', steps)

0 actions:  [[ 0.50091926 -0.97343231  1.04112754 -0.63183081]
 [-0.97618689 -1.49116626  0.76830149  0.98139038]
 [-1.47242124 -0.08242432  0.80782791  0.22936895]
 [-0.67637458  0.253603    0.84113523 -0.72289794]
 [-0.09328509 -0.40599682  0.49906732  0.92424955]]
0 steps:  [ 191  743  935 1087 1354]
1 actions:  [[-0.65391054 -0.19494585  0.25213854 -0.28678172]
 [ 0.24830482 -1.47711351  0.64062696  0.01075097]
 [-0.34412648 -0.77555975  0.76926548  0.25375424]
 [ 0.48528156 -1.31094659  0.751061    1.37163287]
 [ 0.41155573 -1.27272157  0.82978795  1.4134744 ]]
1 steps:  [ 273  560  921 1468 1773]
2 actions:  [[-0.77228525  0.28915375  0.93795097 -0.65307533]
 [ 0.10344208 -0.28073785  0.81987485 -1.07594277]
 [-1.41651883  0.92299004  0.60912794 -0.60436204]
 [-0.40548275  0.93126971  0.64442307 -1.00580912]
 [-0.08949935 -1.19366063  1.0851699  -0.12342456]]
2 steps:  [ 343  637  803 1057 1413]
3 actions:  [[-0.81862987 -1.35074768 -0.41036786  1.45386539]
 [-1.35440403 -0.56723

In [4]:
# open json file
import json
i = 0
with open(f'/media/baoyu/sumsung/rope_2/rope/episode_{i}/property.json') as f:
    data = json.load(f)
data

{'particle_radius': 0.025,
 'num_particles': 1167,
 'length': 83.36616906954923,
 'thickness': 159.5696260319544,
 'dynamic_friction': 0.5593047845816544,
 'cluster_spacing': 7.697491593401359,
 'global_stiffness': 0.0}

In [45]:
for i in range(294):
    end_effector = np.load(f'/media/baoyu/sumsung/rope/episode_0/camera_0/{i}_endeffector.npy')
    print(i, end_effector)

0 [-2.  0.  1.]
1 [0.3118635 0.1690278 1.       ]
2 [0.30339465 0.16380078 1.        ]
3 [0.2949258  0.15857376 1.        ]
4 [0.28645696 0.15334674 1.        ]
5 [0.27798811 0.14811972 1.        ]
6 [0.26951926 0.14289271 1.        ]
7 [0.26105041 0.13766569 1.        ]
8 [0.25258156 0.13243867 1.        ]
9 [0.24411271 0.12721165 1.        ]
10 [0.23564386 0.12198463 1.        ]
11 [0.22717501 0.11675761 1.        ]
12 [0.21870616 0.11153059 1.        ]
13 [0.21023731 0.10630358 1.        ]
14 [0.20176846 0.10107656 1.        ]
15 [0.19329961 0.09584954 1.        ]
16 [0.18483077 0.09062252 1.        ]
17 [0.17636192 0.0853955  1.        ]
18 [0.16789307 0.08016848 1.        ]
19 [0.15942422 0.07494146 1.        ]
20 [0.15095537 0.06971445 1.        ]
21 [0.14248652 0.06448743 1.        ]
22 [0.13401767 0.05926041 1.        ]
23 [0.12554882 0.05403339 1.        ]
24 [0.11707997 0.04880637 1.        ]
25 [0.10861112 0.04357935 1.        ]
26 [0.10014227 0.03835233 1.        ]
27 [0.09

In [40]:
from scipy.spatial.transform import Rotation
rot = Rotation.from_euler('xyz', [0, 0, 90], degrees=True)
# Convert to quaternions and print
rot_quat = rot.as_quat()
rot_quat

array([0.        , 0.        , 0.70710678, 0.70710678])

In [13]:
import numpy as np
x = np.array([3, 4, 2, 1])
idx = np.argsort(x)
print(idx)
x[idx]

[3 2 0 1]


array([1, 2, 3, 4])