In [2]:
import numpy as np
import trimesh
import pyflex

In [2]:
cam_1_particle_fd = '/home/baoyu/2023/unified_dyn_graph/data/shirt/camera_1/episode_0/0_particles.npy'
cam_2_particle_fd = '/home/baoyu/2023/unified_dyn_graph/data/shirt/camera_2/episode_0/0_particles.npy'

In [3]:
# load particles
cam_1_particles = np.load(cam_1_particle_fd)
cam_2_particles = np.load(cam_2_particle_fd)

In [5]:
cam_1_particles

array([-1.2666063e+00,  5.0500000e-01,  5.7655107e-03, ...,
        5.0500000e-01, -2.3049787e-01,  2.6673998e+04], dtype=float32)

In [6]:
cam_2_particles

array([-1.2666380e+00,  5.0500453e-01,  6.0242866e-03, ...,
        5.0500000e-01, -2.3061238e-01,  2.6673998e+04], dtype=float32)

In [7]:
np.random.rand(1, 1, 4)

array([[[0.57987608, 0.54827175, 0.22697347, 0.13771355]]])

In [8]:
wkspc_w = 4
action = -wkspc_w + 2 * wkspc_w * np.random.rand(1, 1, 4)
action

array([[[-3.97005224,  2.03861417,  0.82938875,  2.79637198]]])

In [9]:
action_1 = np.load('/home/baoyu/2023/unified_dyn_graph/data/shirt/actions.npy')
action_2 = np.load('/home/baoyu/2023/unified_dyn_graph/data/shirt/camera_2/actions.npy')

In [11]:
action_1

array([[-0.51280338,  0.51529479,  0.86425962,  1.94707726],
       [ 0.03016625,  0.51443011,  0.52442104,  0.05195693],
       [ 0.32838815,  0.54590392,  1.89548016,  2.40055496],
       [ 0.52853233,  0.52084321,  0.4391928 ,  1.76951812],
       [ 0.08754858,  0.51355934,  0.35972683,  2.21594589]])

In [12]:
action_2

array([[-0.51300204,  0.51535857,  0.86406096,  1.94714104],
       [ 0.02210885,  0.51449007,  0.51636363,  0.0520169 ],
       [ 0.39224148,  0.52836263,  1.95933348,  2.38301367],
       [ 0.49471378,  0.505     ,  0.40537425,  1.75367491],
       [ 0.09445389,  0.55732459,  0.36663213,  2.25971114]])

In [4]:
actions = np.load('/home/baoyu/2023/unified_dyn_graph/data/shirt/actions.npy')
actions = actions.reshape(20, 5, 4)
actions

array([[[ 1.43178247e+00,  1.38900696e+00, -8.01924216e-01,
          3.87438540e-01],
        [ 1.56709200e+00,  1.85465104e+00, -6.65764925e-01,
         -2.70070022e-01],
        [-8.00913105e-02, -4.28860816e-01, -6.50922367e-01,
         -2.01592196e-01],
        [-1.91912641e+00,  1.33047938e+00, -1.20385276e+00,
         -1.83647211e-01],
        [-1.05598323e-01, -1.25467063e+00, -9.82133496e-01,
          6.92412735e-02]],

       [[-1.92484080e+00,  4.70541988e-01, -2.77526787e-01,
         -1.01925867e+00],
        [ 1.61039390e+00, -2.00200040e-01, -2.02322560e-01,
          2.27696366e-01],
        [-1.75909811e+00,  6.67066862e-01, -7.26624278e-03,
          9.07412247e-01],
        [-7.38286596e-01, -5.45156916e-01, -2.10363363e-01,
         -1.32355754e+00],
        [-1.59182076e+00, -1.16449298e+00, -1.86424981e-01,
          2.92483814e-01]],

       [[-3.42525647e-01, -1.01209991e-01,  3.27037280e-01,
          4.47852055e-01],
        [-1.94571346e+00,  4.91384382e-